### ISSUE TITLE
Usage example is not consistent with documentation

### ISSUE THREAD

**Issue by peterkline-es** [BaileyJM02/markdown-to-pdf#1]
The usage example 

```yaml
        with:
          markdown_dir: docs
```

This key of `markdown_dir` does not exist, rather the documentation should reference `input_dir`.  Without `input_dir` the default path is just the GITHUB_WORKSPACE.

**Comment by BaileyJM02** [comment]
Hi, thank you for spotting this, completely missed it. I would also like to thank you for spending time to correct this. :smiley:
