### ISSUE TITLE
Target single markdown file

### ISSUE THREAD

**Issue by BaileyJM02** [BaileyJM02/markdown-to-pdf#27]
As discussed in #26, the input_dir should also accept a single file path. Two options for completing this are the following:
- Check if the path ends in `.md` (or `.markdown`) and if so only pass a return array with a length of one.
- Check if the path is a directory, if not, pass the path into the array directly which will result in a length of one.

<div type='discussions-op-text'>

<sup>Originally posted by @tomking July 16, 2021</sup>
Hello, I see that the action takes an input directory to pull .md files from for conversion. I was wondering if it is possible to target a single .md file rather than an entire directory? I didn't see anything about this in the readme, apologies if I missed it and thank you for your time!</div>

**Comment by tomking** [comment]
Seeing as I was the one who brought this up, I would be happy to take a stab at it if you'd like. I can probably have a pull request in for this in the next day or two just let me know.

**Comment by BaileyJM02** [comment]
@tomking, if you're able to do this that would be awesome, very busy with work so it would definitely be done quicker by someone else 👍. Thank you!

**Comment by tomking** [comment]
@BaileyJM02 What would the correct way to test changes be? I haven't worked on a Github action before so I'm not really sure if there is a standard way that people test?

**Comment by BaileyJM02** [comment]
@tomking, I'm currently trying to set up a `.devcontainer/` using [`act`](https://github.com/nektos/act), unfortunately, I'm stuck waiting for the bug nektos/act#744 to be fixed due to the nature of the Dockerfile.

**Comment by tomking** [comment]
No worries, I have some code done up but I have no idea if it is working at all as I am not even sure how to manually test it as an action (This is the first time I have actually worked with github actions). I spent some time trying to see if I could get it working in my fork to be able to test it but I'm not sure how to setup the Docker container to be able to do that. Would you want me to submit a pull request to the feature branch for this on your repo and go from there?

**Comment by BaileyJM02** [comment]
Merged as of #29
