### ISSUE TITLE
Page breaks for PDF files

### ISSUE THREAD

**Issue by omeganot** [BaileyJM02/markdown-to-pdf#30]
Hello there!  Thanks for the awesome action.  It was simple to set up, and I love the quick concatenation of several folders and directories to pull from, in order, when generating a PDF.  It's great.

I'm curious, would there be a way to configure the action to start a new page in the PDF document for each Markdown file it encounters?  It would help me segment some of my content and make it easier to read, especially with a table of contents.  It seems the converter first generates HTML, then a PDF from that, so I'm not sure what the technique would be to separate pages, but it'd be an awesome feature if possible.  If you have any thoughts let me know, and I'd be happy to help if I can.

**Comment by BaileyJM02** [comment]
Hey @omeganot, thank you for the kind words. Did you find a solution for this in the end?

**Comment by omeganot** [comment]
Hey, sorry for the open/close noise and you're welcome! To be honest, I mixed up which repo I was adding the issue to, though it is a repo which leverages your work for it's action (https://github.com/shrink/actions-document-publish) so the appreciation still holds. :)

Haven't found a solution yet. What I'm hoping for in the end is numerous markdown files compiled into a single PDF, with each input file starting on a new page of the PDF. The other single file solution mentioned above will continue on the same page if a document ends mid-page. I can't figure out how to get multiple PDFs joined together, which may accomplish this task (though, perhaps without a single ToC).

Thanks for checking in, and if you have a direction you could point me I'd greatly appreciate it!
