### ISSUE TITLE
problem with Light Mode and Dark Mode

### ISSUE THREAD

**Issue by dariodenardi** [BaileyJM02/markdown-to-pdf#34]
good job! this GitHub Action is very interesting!

I have a question:

in README it's possible to insert an image with a tag that indicates in which mode it should be viewed:

```
![Light-Mode](./img/img5-light.png#gh-light-mode-only)
![Dark-Mode](./img/img5-dark.png#gh-dark-mode-only)
```

if my pc has light mode, only the first image is chosen otherwise the second. Problem is that both images are inserted in the pdf. solution?

**Comment by BaileyJM02** [comment]
I haven't yet supported this feature - it was new to GH fairly recently. I can look into whether it's possible but it might be an idea of simply using custom CSS:

(presuming you only want the light theme picture)

```css
img[src*="gh-dark-mode-only"] {
    display: none;
}
```

**Comment by dariodenardi** [comment]
Thank you for your answer!

I have tried many time your code but it doesn't work...it was very helpful and I found this solution:

images are inserted in the html in base64 and the tag ```gh-dark-mode-only``` is lost. So I use a class in ```img``` tag:

```
.dark-mode {
    display: none;
}
```

this is a possibile solution
